### ISSUE TITLE
Getting the Length of a Rigid Body

### ISSUE THREAD

**Issue by nkueng** [cmm-20/final-project#3]
Is there a nice way of getting a `RobotRB`'s length other than computing a vector between its parent and child joints?

**Comment by nathanael-k** [comment]
I suppose not: it can have multiple child joints, so it would be hard to define a length. Also, some have end-effectors, and no child joints.

An easy hack would be to write a quick function in RobotRB to give back the distance between the parent node and the first child, just be sure to check if they are both initialized or else you are in risk of dereferencing uninitialized memory. You could even handle the case of "end-effector instead of child joint".

It would work in our specific case, but I am skeptic if it is the right approach. I would keep RobotRB as general as possible, and implement such specific code in a class that only works with your specific robot. For example a new class "spider" that has the "Robot" as a field (or a pointer), and then write all "spider" specific methods in there.
