### ISSUE TITLE
How to use the GeneralizedCoordinatesRobotRepresentation class?

### ISSUE THREAD

**Issue by nkueng** [cmm-20/final-project#6]
I am unsuccessfully trying to get an object of `GeneralizedCoordinatesRobotRepresentation` running in `app.h`. Has anyone (with better C++ skills) managed to instantiate such an object and linked it to our robot? My attempt 
```
GeneralizedCoordinatesRobotRepresentation genCoords = 
 GeneralizedCoordinatesRobotRepresentation(&robot);
```
right after the robot gets instantiated didn't work because the type is supposedly unknown to the compiler. However, since we include `GeneralizedCoordinatesRobotRepresentation.h` in `Robot.cpp` I don't see why the linking doesn't work.

**Update**: I managed to get the above line of code working by including the mentioned header right in `app.h`, but why do I need to do that? Does the inclusion in `Robot.cpp` only work for the scope inside that file?

**Comment by nathanael-k** [comment]
> Does the inclusion in Robot.cpp only work for the scope inside that file?

Basically, yes.

In C++ you usually have a structure with .h files and .cpp files.
In .h files you put all the definitions, basically function and class signatures. This is all the information that you need if you want to reference stuff from other files.
The actual code can then be placed in .cpp files.

Including works recursively (its just copying all the content into the file before compiling).
Note that app.h included Robot.h, which did not include `Gen.....tion.h` 
So there was no way to reach it. If you need to know about the signature of functions in `Gen......tion.h`, in `app.h`, you should also include it there.
You could also have included `Robot.cpp`, which includes `Gen.....tion.h`, but that would be stupid ;)

Beware however of circular includes: it can happen that `class A` has a pointer to `class B`, and `class B` has a pointer to `class A`. If you now just include their header files from both, you will have two problems:

1. infinite recursion: this is why we use include guards
2. if you include `b.h` at the top of `a.h`, `b.h` gets copied and placed there during preprocessing. But since it gets parsed from the top, it will have no idea what `class A` is when reaching that point (the pointer to A that's in B). So it will fail.

The solution to 2) is to use "forward declaration", writing just `class B;`

I just mention it because it happened again to me yesterday, and if it happens the first time it can take quite a time to find the reason why compilation fails :)

**Comment by nkueng** [comment]
> The solution to 2) is to use "forward declaration", writing just class B;

I'm guessing an example of this can be found in `Robot.h`, where `class RobotState;` is stated before denoting it as a `friend class`. 

```
#pragma once

#include "robot/RobotRB.h"
#include "robot/RBJoint.h"
#include "robot/RBEngine.h"
#include "robot/RBUtils.h"

#include "robot/RBRenderer.h"

#include <utils/utils.h>

class RobotState;

/**
    Robots are articulated figures (i.e. tree structures starting at a root)
*/
class Robot {
    friend class RobotState;
    friend class GeneralizedCoordinatesRobotRepresentation;
```

Why is the same not done with `class GeneralizedCoordinatesRobotRepresentation`? How does the compiler know at this point in the code what `GeneralizedCoordinatesRobotRepresentation` is if its signature is not known at this point? 

Also, why don't we need an `#include <robot/RobotState.h>` in this header file?
I am seriously confused as to the division of includes between `Robot.h` and `Robot.cpp`...

**Comment by nathanael-k** [comment]
Well, nobody really likes to concern himself with the `#include`s, so usually you just tinker with it until it works.

> Why is the same not done with class GeneralizedCoordinatesRobotRepresentation? How does the compiler know at this point in the code what GeneralizedCoordinatesRobotRepresentation is if its signature is not known at this point?

Funny enough, the 'friend class GeneralizedCoordinatesRobotRepresentation;' is basically a forward declaration, and therefore the 'class RobotState;' is not needed.

> Also, why don't we need an #include <robot/RobotState.h> in this header file? I am seriously confused as to the division of includes between Robot.h and Robot.cpp...

Think about it the other way: In the header file of a class we have to place everything that any other code needs to know about that class in order to use that class. So we need to know what the function signatures are, what the members are and so on. We explicitly don't care about the implementation.
The ultimate goal is to compile a library that we can call from other places, and for these calls we need to know the information from the header files.

So let's say we build a library that relies heavily on Eigen, but uses only double[] in its function calls. If we want to compile this library, we need to include Eigen, otherwise all our implementation makes no sense.
However, if we call that library after compilation, we never use Eigen, since we don't need to know about what the library does internally. 
Therefore we need to include the header file of our library in our code.
But the header file of our library should **NOT** include Eigen, otherwise it would get used recursively in all projects that use our library. Instead, include it only in the .cpp file of our library. Because there we actually need it.

Does that make sense? Ideally, you include as little stuff as possible in the header file (only the stuff that we need in order for the signatures to make sense). All the other includes your implementation needs should be placed in the .cpp file.
